services:
  django:
    image: rplatform_django
    build: .
    container_name: rplatform_django
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: rplatform.settings.development
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - rplatform_net

  redis:
    image: redis:7
    container_name: rplatform_redis
    ports:
      - "6379:6379"
    networks:
      - rplatform_net

networks:
  rplatform_net:
    driver: bridge
