version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: Qkics-Backend
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: rplatform.settings.production
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    restart: unless-stopped
    network_mode: host