services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: rplatform_django_prod
    env_file:
      - .env.production
    depends_on:
      - redis
      - mysql
    networks:
      - rplatform_net

  redis:
    image: redis:7
    container_name: rplatform_redis_prod
    networks:
      - rplatform_net

  mysql:
    image: mysql:8.0
    container_name: rplatform_mysql_prod
    restart: always
    environment:
      MYSQL_DATABASE: research_platform_db
      MYSQL_USER: prod_db_user
      MYSQL_PASSWORD: strong-db-password
      MYSQL_ROOT_PASSWORD: root-password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - rplatform_net

  nginx:
    image: nginx:alpine
    container_name: rplatform_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/app/staticfiles
    depends_on:
      - django
    networks:
      - rplatform_net

volumes:
  mysql_data:

networks:
  rplatform_net:
    driver: bridge
